# Generated by Django 3.1.5 on 2021-03-03 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterestAccounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
