# Generated by Django 3.1.5 on 2021-03-05 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20210227_1523'),
        ('pinterestAccounts', '0002_delete_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='following',
        ),
        migrations.AddField(
            model_name='account',
            name='followingTag',
            field=models.ManyToManyField(blank=True, related_name='followingTag', to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='account',
            name='followingUser',
            field=models.ManyToManyField(blank=True, related_name='followingUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
