# Generated by Django 3.1.5 on 2021-02-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20210227_1523'),
        ('pin', '0005_pin_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
    ]
