# Generated by Django 3.1.5 on 2021-04-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0006_pin_tag_set'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['title'], name='Pin_title_idx'),
        ),
    ]
