version: '3'

services:
  django:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    command: python manage.py runserver 0:8000 --settings=backend.settings.prod
    ports:
      - "8000:8000"
    working_dir: /djangoProject
    volumes:
    - .:/djangoProject
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx
    container_name : nginx_service
    volumes:
      - ./volumes-nginx:/etc/nginx/conf.d
      - ./volumes/.static_root/:/static
    ports:
      - "80:80"
    depends_on :
      - django