version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --env DJANGO_SETTINGS_MODULE='backend.settings.prod'
    ports:
      - "8000:8000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /djangoProject
    volumes:
    - .:/djangoProject
    expose:
      - "8000"

  nginx:
    image: nginx
    container_name : nginx_service
    volumes:
      - ./volumes-nginx:/etc/nginx/conf.d
      - ./volumes/.static_root/:/static
    ports:
      - "80:80"
    depends_on :
      - django