version: '3'
services:
  django:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    depends_on:
      - redis
    command: python3 manage.py runserver 0:8000 --settings=backend.settings.prod
    ports:
      - "8000:8000"
    working_dir: /djangoProject
    links:
      - redis
    volumes:
    - .:/djangoProject
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx
    container_name : nginx_service
    volumes:
      - ./volumes-nginx:/etc/nginx/conf.d
      - ./volumes/.static_root/:/static
    ports:
      - "80:80"
    depends_on :
      - django
  redis:
    image: redis:alpine
    command: redis-server
  celery:
    restart: always
    build:
      context: .
    command: celery -A backend worker -l info
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.CUT-8
    volumes:
    - .:/djangoProject
    depends_on:
      - redis
      - django
      - nginx
  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: --host=http://django:8000 -f /mnt/locust/locust_files/locust_example.py

#  worker:
#    image: locustio/locust
#    volumes:
#      - ./:/mnt/locust
#    command: -f /mnt/locust/locust_files/locust_example.py --worker --master-host=127.0.0.1:8089
#
#    depends_on:
#      - locust